// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgA2yshOi_gYtfVVGHGIsTgSsRmtVDbdM',
    appId: '1:816989312105:web:bc43d7ebf81b4732d87ef8',
    messagingSenderId: '816989312105',
    projectId: 'the-end-capstone',
    authDomain: 'the-end-capstone.firebaseapp.com',
    storageBucket: 'the-end-capstone.appspot.com',
    measurementId: 'G-2HR2QE3W3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGpOSZQ4YgUAVqehGSddofPoAkaaglGa4',
    appId: '1:816989312105:android:9796002fd603d857d87ef8',
    messagingSenderId: '816989312105',
    projectId: 'the-end-capstone',
    storageBucket: 'the-end-capstone.appspot.com',
  );

}